# Generated by Django 4.1.4 on 2022-12-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('rentage', 'rentage'), ('sale', 'sale'), ('mortgaage', 'mortgage')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('choice', models.CharField(choices=[('Detached', 'Detached'), ('Semi-detached', 'semi-detached'), ('Duplex', 'Duplex'), ('Bungalow', 'Bungalow')], max_length=20)),
                ('date_of_viewing', models.DateField()),
                ('messages', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
